// Curated Florida flagship locations. Station IDs verified against NOAA mdapi.

import type { Location } from "./locations";

export const FL_LOCATIONS: Location[] = [
  {
    slug: "key-west",
    name: "Key West",
    state: "florida",
    stateName: "Florida",
    stationId: "8724580",
    stationName: "Key West",
    lat: 24.556,
    lon: -81.808,
    region: "keys",
    tagline: "The end of the road — flats, wrecks, and tarpon highways",
    intro:
      "Key West is the sportfishing crossroads of North America: bonefish and permit tail on the flats to the east, tarpon pour through the harbor every spring, and the reef and Gulf wrecks are twenty minutes from the dock. The White Street Pier and the flats along the Riviera Canal give shore anglers real shots at flats species without a boat.",
    speciesKeys: ["tarpon", "permit", "bonefish-fl", "mangrove-snapper", "snook"],
    nearby: ["marathon", "naples", "miami"],
    aliases: ["keys", "lower keys", "stock island"],
  },
  {
    slug: "marathon",
    name: "Marathon",
    state: "florida",
    stateName: "Florida",
    stationId: "8723970",
    stationName: "Vaca Key, Florida Bay",
    lat: 24.711,
    lon: -81.107,
    region: "keys",
    tagline: "Middle Keys hub — Seven Mile Bridge and Florida Bay flats",
    intro:
      "Marathon sits at the heart of the Keys with water on every side: Florida Bay's backcountry flats to the north, the Atlantic reef to the south, and the legendary Seven Mile Bridge channels in between. Tarpon stack in the bridge shadows April through July, and the old bridge spans are among the best land-based fishing platforms in America.",
    speciesKeys: ["tarpon", "bonefish-fl", "permit", "mangrove-snapper", "spanish-mackerel"],
    nearby: ["key-west", "miami", "naples"],
    aliases: ["vaca key", "seven mile bridge", "middle keys"],
  },
  {
    slug: "miami",
    name: "Miami",
    state: "florida",
    stateName: "Florida",
    stationId: "8723214",
    stationName: "Virginia Key, Biscayne Bay",
    lat: 25.731,
    lon: -80.162,
    region: "atlantic",
    tagline: "Biscayne Bay — bonefish flats in a skyline's shadow",
    intro:
      "Miami is the only major city in America where you can sight-fish bonefish with a skyline behind you. Biscayne Bay's flats hold bones and permit year-round, tarpon roll along Government Cut on the outgoing tide, and the seawalls and bridges of the bay produce snook and snapper for anglers on foot.",
    speciesKeys: ["bonefish-fl", "tarpon", "snook", "permit", "mangrove-snapper"],
    nearby: ["marathon", "cocoa-beach", "key-west"],
    aliases: ["biscayne bay", "virginia key", "miami beach", "key biscayne"],
  },
  {
    slug: "naples",
    name: "Naples",
    state: "florida",
    stateName: "Florida",
    stationId: "8725110",
    stationName: "Naples",
    lat: 26.132,
    lon: -81.808,
    region: "gulf",
    tagline: "Southwest Gulf — snook beaches and Ten Thousand Islands",
    intro:
      "Naples pairs a famous pier with some of the best snook beach fishing in Florida — summer linesiders cruise the bar just yards off the sand. To the south, the Ten Thousand Islands open into an endless maze of mangroves where redfish, snook, and juvenile tarpon live in the creeks and on the outside bars.",
    speciesKeys: ["snook", "redfish", "speckled-trout", "tarpon", "sheepshead"],
    nearby: ["tampa-bay", "key-west", "marathon"],
    aliases: ["naples pier", "marco island", "ten thousand islands"],
  },
  {
    slug: "tampa-bay",
    name: "Tampa Bay",
    state: "florida",
    stateName: "Florida",
    stationId: "8726520",
    stationName: "St. Petersburg, Tampa Bay",
    lat: 27.761,
    lon: -82.627,
    region: "gulf",
    tagline: "Florida's biggest bay — flats, bridges, and the Skyway",
    intro:
      "Tampa Bay is an inshore fishery on an industrial scale: four hundred square miles of grass flats, mangrove shorelines, and bridge spans. The Skyway Fishing Pier — the world's longest — puts anglers over tarpon-grade water for a few dollars, while the flats from Fort De Soto to Weedon Island hold redfish, snook, and trout every month of the year.",
    speciesKeys: ["snook", "redfish", "speckled-trout", "tarpon", "sheepshead"],
    nearby: ["naples", "cocoa-beach", "pensacola"],
    aliases: ["st petersburg", "st pete", "skyway", "clearwater", "tampa"],
  },
  {
    slug: "cocoa-beach",
    name: "Cocoa Beach",
    state: "florida",
    stateName: "Florida",
    stationId: "8721604",
    stationName: "Trident Pier, Port Canaveral",
    lat: 28.416,
    lon: -80.593,
    region: "atlantic",
    tagline: "Space Coast surf and the Banana River lagoons",
    intro:
      "Cocoa Beach fishes two worlds a mile apart: the Atlantic surf, where pompano and whiting run the troughs all winter, and the Banana River and Mosquito Lagoon behind it — shallow, grassy redfish water famous for some of the biggest reds in Florida. Port Canaveral's jetties and locks concentrate everything that moves along this coast.",
    speciesKeys: ["redfish", "speckled-trout", "pompano", "snook", "tarpon"],
    nearby: ["jacksonville", "miami", "tampa-bay"],
    aliases: ["port canaveral", "space coast", "mosquito lagoon", "banana river"],
  },
  {
    slug: "jacksonville",
    name: "Jacksonville",
    state: "florida",
    stateName: "Florida",
    stationId: "8720218",
    stationName: "Mayport (Bar Pilots Dock)",
    lat: 30.398,
    lon: -81.428,
    region: "atlantic",
    tagline: "First Coast — the St. Johns jetties and marsh creeks",
    intro:
      "Jacksonville's fishing runs on the St. Johns River: the huge granite jetties at Mayport funnel redfish, flounder, and sheepshead on every tide swing, while the marsh creeks behind the beaches hold tailing reds on flood tides. Fall brings the bull red run at the river mouth — heavyweight fish measured in decades, not inches.",
    speciesKeys: ["redfish", "flounder-gulf", "sheepshead", "speckled-trout", "pompano"],
    nearby: ["cocoa-beach", "pensacola", "tampa-bay"],
    aliases: ["mayport", "st johns", "jax", "amelia island"],
  },
  {
    slug: "pensacola",
    name: "Pensacola",
    state: "florida",
    stateName: "Florida",
    stationId: "8729840",
    stationName: "Pensacola",
    lat: 30.404,
    lon: -87.211,
    region: "panhandle",
    tagline: "Panhandle pass fishing and sugar-sand surf",
    intro:
      "Pensacola guards the western door of the Panhandle, where a deep pass connects a huge bay to the whitest surf sand in America. The Pensacola Beach pier is a legend — tarpon, kings, and cobia parade past every spring — while the bay's grass flats and the Three Mile Bridge rubble hold trout, redfish, and sheepshead all year.",
    speciesKeys: ["redfish", "speckled-trout", "pompano", "spanish-mackerel", "flounder-gulf"],
    nearby: ["jacksonville", "tampa-bay", "cocoa-beach"],
    aliases: ["pensacola beach", "gulf breeze", "perdido"],
  },
];
