// Florida inshore species knowledge base — merged into SPECIES in species.ts.

import type { Species } from "./species";

export const FL_SPECIES: Record<string, Species> = {
  snook: {
    key: "snook",
    image: "/species/snook.jpg",
    name: "Common Snook",
    scientific: "Centropomus undecimalis",
    emoji: "🐟",
    seasonMonths: [3, 4, 5, 6, 7, 8, 9, 10],
    seasonLabel: "March – October (check season closures)",
    bait: ["Live pilchards", "Swimbaits", "Topwater plugs", "Flair hawks"],
    techniques:
      "Work dock lights, mangrove edges, and passes on moving water. Summer beach snook cruise the first trough at first light.",
    gearKeys: ["inshore-combo", "braided-line", "fluoro-leader", "swimbait-kit"],
    tempRangeF: [70, 88],
  },
  redfish: {
    key: "redfish",
    image: "/species/redfish.jpg",
    name: "Redfish",
    scientific: "Sciaenops ocellatus",
    emoji: "🐟",
    seasonMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    seasonLabel: "Year-round, best in fall",
    bait: ["Cut mullet", "Live shrimp", "Gold spoons", "Paddle tails"],
    techniques:
      "Sight-fish tailing reds on shallow flats on a flooding tide. Fall schools push bait against oyster bars and grass edges.",
    gearKeys: ["inshore-combo", "swimbait-kit", "circle-hooks", "pliers"],
    tempRangeF: [60, 88],
  },
  "speckled-trout": {
    key: "speckled-trout",
    image: "/species/speckled-trout.jpg",
    name: "Spotted Seatrout",
    scientific: "Cynoscion nebulosus",
    emoji: "🐠",
    seasonMonths: [1, 2, 3, 4, 5, 10, 11, 12],
    seasonLabel: "Year-round, best in cooler months",
    bait: ["Live shrimp under a popping cork", "Soft plastics", "Topwaters"],
    techniques:
      "Drift grass flats in 2–6 feet with a popping cork ahead of the drift. Gator trout hunt alone in skinny water at dawn.",
    gearKeys: ["inshore-combo", "fluoro-leader", "swimbait-kit", "landing-net"],
    tempRangeF: [58, 80],
  },
  tarpon: {
    key: "tarpon",
    image: "/species/tarpon.jpg",
    name: "Tarpon",
    scientific: "Megalops atlanticus",
    emoji: "🐋",
    seasonMonths: [4, 5, 6, 7, 8],
    seasonLabel: "April – August migration",
    bait: ["Live crabs", "Threadfin herring", "Swimbaits"],
    techniques:
      "Stake out passes and beaches during the spring migration — hill tides in the Keys are legendary. Bow to the king when it jumps.",
    gearKeys: ["surf-rod", "braided-line", "circle-hooks", "pliers"],
    tempRangeF: [74, 88],
  },
  "mangrove-snapper": {
    key: "mangrove-snapper",
    image: "/species/mangrove-snapper.jpg",
    name: "Mangrove Snapper",
    scientific: "Lutjanus griseus",
    emoji: "🐠",
    seasonMonths: [5, 6, 7, 8, 9, 10],
    seasonLabel: "Year-round, best in summer",
    bait: ["Live shrimp", "Pilchards", "Cut bait on light leader"],
    techniques:
      "Fish structure — docks, bridges, mangrove roots — with the lightest leader you can get away with. They see everything.",
    gearKeys: ["inshore-combo", "fluoro-leader", "circle-hooks", "tackle-bag"],
    tempRangeF: [70, 88],
  },
  pompano: {
    key: "pompano",
    image: "/species/pompano.jpg",
    name: "Florida Pompano",
    scientific: "Trachinotus carolinus",
    emoji: "🐟",
    seasonMonths: [1, 2, 3, 4, 10, 11, 12],
    seasonLabel: "Fall – spring surf runs",
    bait: ["Sand fleas", "Fresh shrimp", "Pompano jigs", "Fishbites"],
    techniques:
      "Surf fish the troughs on an incoming tide with sand fleas — the Florida winter classic. Look for diving birds over sandbars.",
    gearKeys: ["surf-rod", "carolina-kit", "sand-spike", "cooler"],
    tempRangeF: [65, 78],
  },
  sheepshead: {
    key: "sheepshead",
    image: "/species/sheepshead.jpg",
    name: "Sheepshead",
    scientific: "Archosargus probatocephalus",
    emoji: "🐠",
    seasonMonths: [1, 2, 3, 4, 11, 12],
    seasonLabel: "Winter – early spring",
    bait: ["Fiddler crabs", "Shrimp", "Barnacles"],
    techniques:
      "Fish tight to pilings and rocks — the bite is a subtle tick. Set the hook the instant you feel weight; they steal baits for a living.",
    gearKeys: ["inshore-combo", "circle-hooks", "pliers", "tackle-bag"],
    tempRangeF: [55, 75],
  },
  "spanish-mackerel": {
    key: "spanish-mackerel",
    image: "/species/spanish-mackerel.jpg",
    name: "Spanish Mackerel",
    scientific: "Scomberomorus maculatus",
    emoji: "🐟",
    seasonMonths: [3, 4, 5, 9, 10, 11],
    seasonLabel: "Spring and fall runs",
    bait: ["Silver spoons", "Gotcha plugs", "Live pilchards"],
    techniques:
      "Find birds working bait and cast fast-moving metal through the frenzy. Wire or heavy fluoro — their teeth are scissors.",
    gearKeys: ["inshore-combo", "jig-assort", "braided-line", "pliers"],
    tempRangeF: [68, 82],
  },
  "flounder-gulf": {
    key: "flounder-gulf",
    image: "/species/flounder-gulf.jpg",
    name: "Gulf Flounder",
    scientific: "Paralichthys albigutta",
    emoji: "🐠",
    seasonMonths: [4, 5, 9, 10, 11],
    seasonLabel: "Spring and fall, best in the fall run",
    bait: ["Bull minnows", "Live shrimp", "Gulp on a jighead"],
    techniques:
      "Drag baits slowly across sandy potholes and channel edges. Count to three on the bite before setting — they chew first.",
    gearKeys: ["inshore-combo", "circle-hooks", "landing-net", "fluoro-leader"],
    tempRangeF: [62, 80],
  },
  "bonefish-fl": {
    key: "bonefish-fl",
    image: "/species/bonefish-fl.jpg",
    name: "Bonefish",
    scientific: "Albula vulpes",
    emoji: "🐟",
    seasonMonths: [3, 4, 5, 9, 10, 11],
    seasonLabel: "Spring and fall, tide-dependent",
    bait: ["Live shrimp", "Small crabs", "Bonefish jigs"],
    techniques:
      "Pole or wade the flats on a flooding tide and look for tails and nervous water. Long, quiet casts — the gray ghost spooks at shadows.",
    gearKeys: ["inshore-combo", "fluoro-leader", "pliers", "tackle-bag"],
    tempRangeF: [72, 88],
  },
  permit: {
    key: "permit",
    image: "/species/permit.jpg",
    name: "Permit",
    scientific: "Trachinotus falcatus",
    emoji: "🐟",
    seasonMonths: [3, 4, 5, 6, 9, 10],
    seasonLabel: "Spring and fall on the flats",
    bait: ["Live crabs", "Crab flies", "Small jigs"],
    techniques:
      "A live crab drifted ahead of a tailing fish is the classic play. The most maddening — and most rewarding — fish on the flats.",
    gearKeys: ["inshore-combo", "fluoro-leader", "landing-net", "pliers"],
    tempRangeF: [72, 88],
  },
};
